version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=hz7c0qa3rc3)r!ix(*d-rxz%_*!_@#x^!i0w982f1=@59z-h+4
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/data
    environment:
      POSTGRES_DB: company-manager-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

volumes:
  postgres-data:
